MyLotto/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url('', include('drawings.urls', namespace='drawings')),
    url(r'^/maintainDrawing/(?P<drawingId>\d+).+', include('drawings.urls', namespace='drawings')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^submit/', include('drawings.urls', namespace='drawings')),
)

drawings/urls.py
from django.conf.urls import patterns, url
from drawings import views

urlpatterns = patterns(
    '',

    url(r'^$', views.index, name='index'),

    url(r'^viewTickets/viewDrawings/(?P<ticketId>\d+)$', views.viewDrawings, name='viewDrawings'),

    url(r'^.+viewDrawings/(?P<ticketId>\d+)$', views.viewDrawings, name='viewDrawings'),

    url(r'^viewTickets/$', views.viewTickets, name='viewTickets'),

    url(r'^.+maintainDrawing/(?P<drawingId>\d+)$', views.maintainDrawing, name='maintainDrawing'),

    url(r'^submit/$', views.addDrawing, name='addDrawing'),

    url(r'^viewOfficial/$', views.addDrawing, name='addDrawing'),
)

drawings/models.py
from django.db import models


class LottoTicket(models.Model):
    ticket_title = models.CharField(max_length=50)
    date_purchased = models.DateField('Data Purchased')
    number_of_draws = models.IntegerField('Number of Draws')
    multiplier_ind = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.date_purchased)


class Drawing(models.Model):
    lotto_ticket = models.ForeignKey(LottoTicket)
    val1 = models.IntegerField()
    val2 = models.IntegerField()
    val3 = models.IntegerField()
    val4 = models.IntegerField()
    val5 = models.IntegerField()
    mega_ball = models.IntegerField()

    def __unicode__(self):
        return unicode(self.id)


class OfficialDrawing(models.Model):
    drawing_date = models.DateTimeField('Drawing Date', primary_key=True)
    val1 = models.IntegerField()
    val2 = models.IntegerField()
    val3 = models.IntegerField()
    val4 = models.IntegerField()
    val5 = models.IntegerField()
    mega_ball = models.IntegerField()
    multiplier = models.IntegerField()

    def __unicode__(self):
        return unicode(self.drawing_date)

drawings/forms.py
import collections
from datetime import datetime, timedelta
from django.forms import ModelForm, forms
from drawings.models import Drawing, OfficialDrawing


class drawingForm(ModelForm):
    class Meta:
        model = Drawing
        fields = ['lotto_ticket', 'val1', 'val2', 'val3', 'val4', 'val5', 'mega_ball']


class viewDrawingsForm(forms.Form):
    def getApplicableOfficialDrawings(self, purchaseDate, numberOfDrawings):
        officialDrawings = []
        iterationDate = self.getNextDrawingDate(purchaseDate)
        drawingsRecorded = 0
        while iterationDate is not None and numberOfDrawings > drawingsRecorded:
            try:
                officialDrawings.append(OfficialDrawing.objects.get(drawing_date=iterationDate))
                iterationDate += timedelta(days=1)
                iterationDate = self.getNextDrawingDate(iterationDate)
                drawingsRecorded += 1
            except:
                return officialDrawings
        return officialDrawings

    # noinspection PyBroadException
    def getNextDrawingDate(self, iterationDate):
        while iterationDate <= datetime.date(OfficialDrawing.objects.latest('drawing_date').drawing_date):
            try:
                OfficialDrawing.objects.get(drawing_date=iterationDate)
                return iterationDate
            except:
                iterationDate = iterationDate+timedelta(days=1)
        return None

    def calculateWinningValue(self, numberCount, hitMegaBallInd):
        payout = 0
        if hitMegaBallInd:
            if numberCount == 0:
                payout = '1'
            if numberCount == 1:
                payout = '2'
            if numberCount == 2:
                payout = '5'
            if numberCount == 3:
                payout = '50'
            if numberCount == 4:
                payout = '5,000'
            if numberCount == 5:
                payout = 'JACKPOT'
        else:
            if numberCount == 3:
                payout = '5'
            if numberCount == 4:
                payout = '500'
            if numberCount == 5:
                payout = '1,000,000'
        return payout

    def calculateMatchedNumbers(self, ticketDrawings, officialDrawing):
        officalDrawingRegularNumbersList = [officialDrawing.val1, officialDrawing.val2, officialDrawing.val3, officialDrawing.val4, officialDrawing.val5]
        matchedNumbersDict = collections.OrderedDict()
        for ticketDrawing in ticketDrawings.all():
            regularNumbersMatched = 0
            megaBallMatched = False
            if ticketDrawing.val1 in officalDrawingRegularNumbersList:
                regularNumbersMatched += 1
            if ticketDrawing.val2 in officalDrawingRegularNumbersList:
                regularNumbersMatched += 1
            if ticketDrawing.val3 in officalDrawingRegularNumbersList:
                regularNumbersMatched += 1
            if ticketDrawing.val4 in officalDrawingRegularNumbersList:
                regularNumbersMatched += 1
            if ticketDrawing.val5 in officalDrawingRegularNumbersList:
                regularNumbersMatched += 1
            if ticketDrawing.mega_ball == officialDrawing.mega_ball:
                megaBallMatched = True
            if regularNumbersMatched or megaBallMatched:
                winningValue = self.calculateWinningValue(regularNumbersMatched, megaBallMatched)
                if winningValue:
                    matchedNumbersDict[ticketDrawing] = winningValue
        return matchedNumbersDict

    def generatePayoutDictionary(self, lottoTicket, applicableDrawings):
        payoutDict = collections.OrderedDict()
        for officialDrawing in applicableDrawings:
            matchedNumbersDict = self.calculateMatchedNumbers(lottoTicket.drawing_set, officialDrawing)
            payoutDict[officialDrawing.drawing_date] = matchedNumbersDict
        return payoutDict

drawings/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.utils import timezone
from drawings.models import LottoTicket, Drawing
from forms import viewDrawingsForm
from django.core.mail import send_mail


def index(request):
    print "in index"
    return render(request, 'drawings/index.html')


def maintainDrawing(request, drawingId):
    print "in maintainDrawing"
    context = RequestContext(request, {'drawing': Drawing.objects.get(id=drawingId), 'ticketId': request.POST.get('ticketId')})
    return render(request, 'drawings/maintainDrawing.html', context)


def viewDrawings(request, ticketId):
    print "in viewDrawings"
    lottoTicket = LottoTicket.objects.get(id=ticketId)
    drawingsForm = viewDrawingsForm()
    context = RequestContext(request, {'lotto_ticket': LottoTicket.objects.get(id=ticketId),
                                       'official_drawings': viewDrawingsForm.getApplicableOfficialDrawings(drawingsForm,lottoTicket.date_purchased, lottoTicket.number_of_draws),
                                       'winningDrawingsTable': drawingsForm.generatePayoutDictionary(lottoTicket, viewDrawingsForm.getApplicableOfficialDrawings(drawingsForm,lottoTicket.date_purchased, lottoTicket.number_of_draws))})
    return render(request, 'drawings/viewDrawings.html', context)


def viewTickets(request):
    print "in viewTickets"
    allTickets = LottoTicket.objects.all()
    context = {'latest_ticket_list': allTickets}
    return render(request, 'drawings/viewTickets.html', context)


def addDrawing(request): #, number2, number3, number4, number5, megaball): # todo: make functional, or delete
    print "in addDrawing"
    drawing = Drawing(drawing_date=timezone.now())
    drawing.val1 = 11
    drawing.val2 = 22
    drawing.val3 = 33
    drawing.val4 = 44
    drawing.val5 = 55
    drawing.mega_ball = 66
    drawing.save()
    return index(request)

drawings/templates/drawings/index.html
<input type="button" onclick="location.href ='/viewTickets/'" value="View Tickets" />

drawings/templates/drawings/maintainDrawing.html
<form method="post" action="{%  url 'drawings:addDrawing' %}" >
    {% csrf_token %}
    <table>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>1st Number</td>
            <td><input type='text' name='number1' maxlength="2" value="{{ drawing.val1 }}" /></td>
        </tr>
        <tr>
            <td>2nd Number</td>
            <td><input type='text' name='number2' maxlength="2" value="{{ drawing.val2 }}" /></td>
        </tr>
        <tr>
            <td>3rd Number</td>
            <td><input type='text' name='number3' maxlength="2" value="{{ drawing.val3 }}" /></td>
        </tr>
        <tr>
            <td>4th Number</td>
            <td><input type='text' name='number4' maxlength="2" value="{{ drawing.val4 }}" /></td>
        </tr>
        <tr>
            <td>5th Number</td>
            <td><input type='text' name='number5' maxlength="2" value="{{ drawing.val5 }}" /></td>
        </tr>
        <tr>
            <td>Mega Ball</td>
            <td><input type='text' name='megaball' maxlength="2" value="{{ drawing.mega_ball }}" /></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><input type='submit' name='submitButton' value='Submit' /></td>
        </tr>
    </table>
{#    <input type="button" onclick='location.href ="viewDrawings/{{ drawing.lotto_ticket.id }}"' value="View Drawings" />#}
{#    <input type="button" onclick=location.href ="{% url 'drawings:viewDrawings' drawing.lotto_ticket.id %}" value="View Drawings" />#}
</form>

drawings/templates/drawings/viewDrawings.html
{% if lotto_ticket %}
    <h2 style="margin-left:25px;">{{ lotto_ticket.ticket_title }}</h2>
    <table border="1" style="border-style:solid; margin-left:25px; margin-top:25px;" >
        <tr>
            <th>&nbsp;#1&nbsp;</th>
            <th>&nbsp;#2&nbsp;</th>
            <th>&nbsp;#3&nbsp;</th>
            <th>&nbsp;#4&nbsp;</th>
            <th>&nbsp;#5&nbsp;</th>
            <th>&nbsp;MegaBall&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        {% for drawing in lotto_ticket.drawing_set.all %}
            <tr style="text-align: center">
                <td>{{ drawing.val1 }}</td>
                <td>{{ drawing.val2 }}</td>
                <td>{{ drawing.val3 }}</td>
                <td>{{ drawing.val4 }}</td>
                <td>{{ drawing.val5 }}</td>
                <td>{{ drawing.mega_ball }}</td>
                <td><a href="maintainDrawing/{{ drawing.id }}">Edit</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No drawings are available.</p>
{% endif %}
{#<input type="button" onclick="location.href ='addDrawing/'" value="Add Drawing" />#}
<br />
{% if official_drawings %}
    <h2 style="margin-left:25px;">Official Drawings To Date</h2>
    <table border="1" style="border-style:solid; margin-left:25px; margin-top:25px;" >
        <tr>
            <th>&nbsp;Date&nbsp;</th>
            <th>&nbsp;#1&nbsp;</th>
            <th>&nbsp;#2&nbsp;</th>
            <th>&nbsp;#3&nbsp;</th>
            <th>&nbsp;#4&nbsp;</th>
            <th>&nbsp;#5&nbsp;</th>
            <th>&nbsp;MegaBall&nbsp;</th>
            <th>&nbsp;Multiplier&nbsp;</th>
        </tr>
        {% for officialDrawing in official_drawings %}
            <tr style="text-align: center">
                <td>{{ officialDrawing.drawing_date | date:"DATE_FORMAT" }}</td>
                <td>{{ officialDrawing.val1 }}</td>
                <td>{{ officialDrawing.val2 }}</td>
                <td>{{ officialDrawing.val3 }}</td>
                <td>{{ officialDrawing.val4 }}</td>
                <td>{{ officialDrawing.val5 }}</td>
                <td>{{ officialDrawing.mega_ball }}</td>
                <td>{{ officialDrawing.multiplier }}x</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p style="margin-left:25px;">No official drawings are available.</p>
{% endif %}

{% if winningDrawingsTable %}
    <h2 style="margin-left:25px;">Winning Draws</h2>
    <table border="1" style="border-style:solid; margin-left:25px; margin-top:25px;" >
        <tr>
            <th>&nbsp;Date&nbsp;</th>
            <th>&nbsp;#1&nbsp;</th>
            <th>&nbsp;#2&nbsp;</th>
            <th>&nbsp;#3&nbsp;</th>
            <th>&nbsp;#4&nbsp;</th>
            <th>&nbsp;#5&nbsp;</th>
            <th>&nbsp;MegaBall&nbsp;</th>
            <th>&nbsp;Winning Amount&nbsp;</th>
        </tr>
        {% for k,v in winningDrawingsTable.items%}
                {% if v.items %}
                    {% for key,value in v.items %}
                        <tr style="text-align: center">
                        <td>{{ k | date:"DATE_FORMAT" }}</td>
                        <td>{{ key.val1 }}</td>
                        <td>{{ key.val2 }}</td>
                        <td>{{ key.val3 }}</td>
                        <td>{{ key.val4 }}</td>
                        <td>{{ key.val5 }}</td>
                        <td>{{ key.mega_ball }}</td>
                        <td>${{ value }}</td>
                    {% endfor %}
                {% else %}
                    <tr style="text-align: center">
                    <td>{{ k | date:"DATE_FORMAT" }}</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                {% endif %}
                </tr>
        {% endfor %}
    </table>
{% endif %}
<input type="button" onclick="location.href ='/'" value="Home" style="margin-left:25px; width:100px;" />

drawings/templates/drawings/viewOfficialDrawings.html
{% if OfficialDrawing.objects.all %}
    <table border="1" style="border-style:solid; margin-left:25px; margin-top:25px;" >
        <tr>
            <th>&nbsp;Date&nbsp;</th>
            <th>&nbsp;#1&nbsp;</th>
            <th>&nbsp;#2&nbsp;</th>
            <th>&nbsp;#3&nbsp;</th>
            <th>&nbsp;#4&nbsp;</th>
            <th>&nbsp;#5&nbsp;</th>
            <th>&nbsp;MB&nbsp;</th>
            <th>&nbsp;Multiplier&nbsp;</th>
        </tr>
        {% for officialDrawing in OfficialDrawing.objects.all %}
            <tr style="text-align: center">
                <td>{{ officialDrawing.drawing_date }}</td>
                <td>{{ officialDrawing.val1 }}</td>
                <td>{{ officialDrawing.val2 }}</td>
                <td>{{ officialDrawing.val3 }}</td>
                <td>{{ officialDrawing.val4 }}</td>
                <td>{{ officialDrawing.val5 }}</td>
                <td>{{ officialDrawing.mega_ball }}</td>
                <td>{{ lotto_ticket.multiplier }}x</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p style="margin-left:25px;">No official drawings are available.</p>
{% endif %}

drawings/templates/drawings/viewTickets.html
{% if latest_ticket_list %}
    <ul>
        {% for ticket in latest_ticket_list %}
            <li><a href="viewDrawings/{{ ticket.id }}">{{ ticket.ticket_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No tickets are available.</p>
{% endif %}
{#<input type="button" onclick="location.href ='/addTicket/'" value="Add Ticket" />#}
<br />
<input type="button" onclick="location.href ='/'" value="Home" />